# Use Java 17 JDK
FROM eclipse-temurin:17-jdk

# Set working directory
WORKDIR /app

# Copy everything
COPY . .

# Give mvnw execute permission
RUN chmod +x mvnw

# Build the Spring Boot JAR
RUN ./mvnw clean package -DskipTests

# Expose port (Railway will set $PORT)
EXPOSE 8080

# Run the JAR
# Use the actual JAR name generated by Maven
CMD ["java", "-jar", "target/Rapid_Global-0.0.1-SNAPSHOT.jar"]